### ISSUE TITLE
undefined method `desc' for Fluent::GelfInput:Class

### ISSUE THREAD

**Issue by geosone** [MerlinDMC/fluent-plugin-input-gelf#1]
looks liek there is a bug:

```
[....] Starting fluent : fluent2016-06-26 08:28:46 +0200 [error]: fluent/supervisor.rb:322:rescue in main_process: unexpected error error="undefined method `desc' for Fluent::GelfInput:Class"
  2016-06-26 08:28:46 +0200 [error]: fluent/supervisor.rb:280:fork: /usr/lib/ruby/vendor_ruby/fluent/plugin/in_gelf.rb:19:in `<class:GelfInput>'
  2016-06-26 08:28:46 +0200 [error]: fluent/supervisor.rb:280:fork: /usr/lib/ruby/vendor_ruby/fluent/plugin/in_gelf.rb:10:in `<module:Fluent>'
  2016-06-26 08:28:46 +0200 [error]: fluent/supervisor.rb:280:fork: /usr/lib/ruby/vendor_ruby/fluent/plugin/in_gelf.rb:9:in `<top (required)>'
  2016-06-26 08:28:46 +0200 [error]: fluent/supervisor.rb:280:fork: /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  2016-06-26 08:28:46 +0200 [error]: fluent/supervisor.rb:280:fork: /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  2016-06-26 08:28:46 +0200 [error]: fluent/supervisor.rb:280:fork: /usr/lib/ruby/vendor_ruby/fluent/plugin.rb:85:in `block in load_plugin_dir'
  2016-06-26 08:28:46 +0200 [error]: fluent/supervisor.rb:280:fork: /usr/lib/ruby/vendor_ruby/fluent/plugin.rb:83:in `each'
  2016-06-26 08:28:46 +0200 [error]: fluent/supervisor.rb:280:fork: /usr/lib/ruby/vendor_ruby/fluent/plugin.rb:83:in `load_plugin_dir'
  2016-06-26 08:28:46 +0200 [error]: fluent/supervisor.rb:280:fork: /usr/lib/ruby/vendor_ruby/fluent/plugin.rb:78:in `load_plugins'
  2016-06-26 08:28:46 +0200 [error]: fluent/supervisor.rb:280:fork: /usr/lib/ruby/vendor_ruby/fluent/engine.rb:43:in `init'
  2016-06-26 08:28:46 +0200 [error]: fluent/supervisor.rb:280:fork: /usr/lib/ruby/vendor_ruby/fluent/supervisor.rb:479:in `init_engine'
  2016-06-26 08:28:46 +0200 [error]: fluent/supervisor.rb:280:fork: /usr/lib/ruby/vendor_ruby/fluent/supervisor.rb:139:in `block in start'
  2016-06-26 08:28:46 +0200 [error]: fluent/supervisor.rb:280:fork: /usr/lib/ruby/vendor_ruby/fluent/supervisor.rb:306:in `call'
  2016-06-26 08:28:46 +0200 [error]: fluent/supervisor.rb:280:fork: /usr/lib/ruby/vendor_ruby/fluent/supervisor.rb:306:in `main_process'
  2016-06-26 08:28:46 +0200 [error]: fluent/supervisor.rb:280:fork: /usr/lib/ruby/vendor_ruby/fluent/supervisor.rb:281:in `block in supervise'
  2016-06-26 08:28:46 +0200 [error]: fluent/supervisor.rb:280:fork: /usr/lib/ruby/vendor_ruby/fluent/supervisor.rb:280:in `fork'
  2016-06-26 08:28:46 +0200 [error]: fluent/supervisor.rb:280:fork: /usr/lib/ruby/vendor_ruby/fluent/supervisor.rb:280:in `supervise'
  2016-06-26 08:28:46 +0200 [error]: fluent/supervisor.rb:280:fork: /usr/lib/ruby/vendor_ruby/fluent/supervisor.rb:137:in `start'
  2016-06-26 08:28:46 +0200 [error]: fluent/supervisor.rb:280:fork: /usr/lib/ruby/vendor_ruby/fluent/command/fluentd.rb:167:in `<top (required)>'
  2016-06-26 08:28:46 +0200 [error]: fluent/supervisor.rb:280:fork: /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  2016-06-26 08:28:46 +0200 [error]: fluent/supervisor.rb:280:fork: /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  2016-06-26 08:28:46 +0200 [error]: fluent/supervisor.rb:280:fork: /usr/bin/fluentd:6:in `<main>'
 failed!
```

**Comment by MerlinDMC** [comment]
I tried to reproduce this but was unable to.
Would be nice to know how to get it to break in this way if the problem still persists.

**Comment by geosone** [comment]
it was my fault it was an older verison of fluentd after the update it worked
