### ISSUE TITLE
plugin cant read gelf from nxlog-ce

### ISSUE THREAD

**Issue by geosone** [MerlinDMC/fluent-plugin-input-gelf#2]
`2016-07-06 16:18:23 +0200 [warn]: Gelfd failed to parse a message error="Failed to decode data: buffer error"
  2016-07-06 16:18:23 +0200 [warn]: /usr/lib/ruby/vendor_ruby/gelfd/zlib_parser.rb:10:in`rescue in parse'
  2016-07-06 16:18:23 +0200 [warn]: /usr/lib/ruby/vendor_ruby/gelfd/zlib_parser.rb:6:in `parse'
  2016-07-06 16:18:23 +0200 [warn]: /usr/lib/ruby/vendor_ruby/gelfd/parser.rb:8:in`parse'
  2016-07-06 16:18:23 +0200 [warn]: /usr/lib/ruby/vendor_ruby/fluent/plugin/in_gelf.rb:73:in `receive_data'
  2016-07-06 16:18:23 +0200 [warn]: /usr/lib/ruby/vendor_ruby/fluent/plugin/socket_util.rb:46:in`call'
  2016-07-06 16:18:23 +0200 [warn]: /usr/lib/ruby/vendor_ruby/fluent/plugin/socket_util.rb:46:in `on_readable'
  2016-07-06 16:18:23 +0200 [warn]: /usr/lib/ruby/vendor_ruby/cool.io/io.rb:186:in`on_readable'
  2016-07-06 16:18:23 +0200 [warn]: /usr/lib/ruby/vendor_ruby/cool.io/loop.rb:88:in `run_once'
  2016-07-06 16:18:23 +0200 [warn]: /usr/lib/ruby/vendor_ruby/cool.io/loop.rb:88:in`run'
  2016-07-06 16:18:23 +0200 [warn]: /usr/lib/ruby/vendor_ruby/fluent/plugin/in_gelf.rb:65:in `run'
`
if the udp package is comming from nxlog-ce the plugin has buffer problems. the logs for testing are piped logs from apche 2.2/2.4 to an nxlog socket and then forwarded to the the fluent server wiht the gelf input https://gist.github.com/geosone/88fa055294ec6d90d19278adc1e5c43c

**Comment by sergey-tarasov-iqoption** [comment]
Any progress? :-)
